version: 1

formatters:
  brief:
    format: '%(levelname)s: $(message)'
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s: %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: brief
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: default
    file: log.log
    maxBytes: 20971520 #20 mb
    backupCount: 5

loggers:
  default:
    level: DEBUG
    handlers: [console,file]
    propagate: no

root:
  level: DEBUG
  handlers: [console]